### ISSUE TITLE
TO DO: Set up the Django environment

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#14]
#Tasks
- [x] Install Django
- [x] Install the gunicorn server
- [x] Install dj_database_url
- [x] Install psycopg2
- [x] Install cloudinairy
- [x] Create the requirements.txt
- [x] Create the Django Project (itrain)
- [x] Create the main app
- [x] Create the setup app
- [x] Migrate the database

# Acceptance Criteria
- All installations are listed with the command _pip list_.
- The database runs with _python3 manage.py runserver_.

# Epic
Belongs to Epic #2
