### ISSUE TITLE
TO DO: Start deployment to Heroku

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#15]
#Tasks
- [x] Create the app on heroku
- [x] Add a postgresql database
- [x] Copy the database_url config var to the env.py
- [x] Set the secret_key in env.py and heroku 
- [x] Update the settings.py
- [x] Migrate the database

# Acceptance Criteria
- The database is visible on Heroku
- 
# Epic
Belongs to Epic #2
