### ISSUE TITLE
TO DO: Create folders for the templates, media and static files

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#16]
#Tasks
- [x] Create a template folder
- [x] Create a static folder with a css and a js folder
- [x] Update settings.py

# Acceptance Criteria
- The necessary folders are present in the project

# Epic
Belongs to Epic #2
