### ISSUE TITLE
TO DO: Finish deployment to Heroku

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#17]
#Tasks
- [x] Set config var disable_collect static to 1 in Heroku
- [x] Create a procfile
- [x] Update the procfile
- [x] Update settings.py: template_dir, templates and allowed_hosts
- [x] Connect the heroku app to github and Deploy branch.

# Acceptance Criteria
- The app i up and running on Heroku!(yeehaw!)

# Epic
Belongs to Epic #2
