### ISSUE TITLE
TO DO: Set up the Cloudinary app

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#18]
#Tasks
- [x] Copy the CLOUDINARY_URL from Cloudinary to env.py
- [x] Copy the CLOUDINARY_URL from Cloudinary to Heroku
- [x] Add Cloudinary to settings.py

# Acceptance Criteria
-
-
# Epic
Belongs to Epic #2
