### ISSUE TITLE
To do: Test unit models

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#24]
#Tasks
- [x] Create a testmodels.py file in the setup app
- [x] Write a test case for the exercise unit.
- [x] Write a test case for the reps unit.
- [x] Repeat until the models are fully tested. 

# Acceptance Criteria
- Coverage shows a 100% test coverage. 
-
# Epic
Belongs to Epic #21
