### ISSUE TITLE
USER STORY:  ~~Create~~ Edit exercise

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#25]
As an **~~authorized user~~** I can **create new exercises** so that **I can reuse them in workouts**
The authorization part will come later.
# Tasks
- [x] Set up the model for exercises
- [x] Add the model to admin.py
- [x] create a view: *ExerciseList*
- [x] Create a template: *exercises*
- [x] Create a form: *ExerciseForm*
- [x] Create a view: *EditExercise*
- [x] Create a template: *edit_exercise*
- [x] Test models, forms and views
  
# Acceptance Criteria
- The page /exercises renders
- All exercises are listed on the /exercises page
- ~~I can create a new empty exercise record by clicking **Create New Exercise**~~
- The page /edit_exercise renders automatically
- ~~The form on the edit exercise page edits the new exercise.~~
- I can pick an exercise from the list and edit it
- The exercise page renders automatically when the form on the /edit_exercise page is submitted.
- The changes made in the form edits the exercise in the database.

- 100% coverage in coverage report
- All tests are a pass

# Epic
Belongs to Epic #9
