### ISSUE TITLE
TO DO: Finish the README.md file

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#3]
As a **developer** I **write a README.md file** so that **interested readers can get an understanding of my project**

# Tasks
- [x] Create the structure of the README.md
- [x] Add wireframes
- [x] Add user stories
- [x] Add responsiveness image
- [x] Add validation results
- [x] List all existing and future features
- [x] List all used technologies including frameworks and libraries
- [x] Add results from a colour contrast check
- [x] Describe the deployment procedure
- [x] Add Credits

# Acceptance Criteria
- The content meets all the requirements from CI for PP4.

# Epic
Belongs to Epic #1
