### ISSUE TITLE
USER STORY: Create Exercise

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#30]
As a **user** I can **create new exercises** so that **I can reuse them in workouts**

After som effort to try to create exercises via a modal. I had to give up and alter the tasks below to instead consist of making a separate page for creating a new exercise. The outlined task and acceptance criteria below has been replaced by an appropriate replacement.

# Tasks
~~ - [ ] Add button and modal to exercise page to create new Exercise~~
- [x] Add button to exercise page to create new Exercise
- [x] Add view to create new exercise
- [x] Add template for new exercise
- [x] Add link on urls.py
- [x] Adjust model for exercise to give a new exercise a default value for unit
- [x] Adjust the testing files to include the create functionality
  
# Acceptance Criteria
- There is a button on the exercises page from where a new exercise can be created
- A modal to create a new exercise opens when the button is clicked.
- The user is redirected to the edit exercise page to complete the creation 
- The new exercise is successfully saved to the database
- The complete report is 100% complete.

# Epic
Belongs to Epic #9
