### ISSUE TITLE
USER STORY: Delete exercise

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#31]
As a **user** I can **delete exercises** so that **I can have control over the exercises I want to keep**
# Tasks
- [x] Add delete exercise view to views.py
- [x] Add delete exercise url to urls.py
- [x] Add button to the exercise list to delete a specific exercise on exercises.html
- [x] Add test to test the delete function
  
# Acceptance Criteria
- An exercise can be deleted
- Testing of the delete feature is covered in coverage with 100%

# Epic
Belongs to Epic #9
