### ISSUE TITLE
USER STORY: Create workout

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#32]
As a **user** I can **create workouts and populate them with exercises** so that **I can reuse them in sessions**
# Tasks
- [x] Add workout model
- [x] Add collection model
- [x] Add a form for creating a workout
- [x] Add view for creating a workout
- [x] Add view for listing workouts
- [x] Add urls to url.py
- [x] Create template for showing workouts
- [x] Create a template for creating a workout
- [x] Update admin.py to show the workouts
- [x] Test the workout models, form and views
  
# Acceptance Criteria
- The page /workouts renders
- All workouts are listed on the /workouts page
- The /create workout page is rendered when pushing the create workout button
- The workout page is automatically rendered when the create workout form is submitted.
- A new workout is actually created in the database when the form is submitted.
- 100% coverage in coverage report
- All tests are a pass.

# Epic
Belongs to Epic #8
