### ISSUE TITLE
USER STORY: Edit Workout

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#33]
As a **user** I can **edit a workout** so that ** I can update an existing workout**
# Tasks
- [x] Create a view for editing workout
- [x] Create a template for editing a workout
- [x] Update the urls,py file with the edit_workout url
- [ ] ~~Test the view and template rendering~~
  
# Acceptance Criteria
- The edit workout page is rendering correctly
- When submitting the form the workout page is rendered
- The edited workout is actually changed in the database

# Epic
Belongs to Epic #8
