### ISSUE TITLE
USER STORY: Delete Workout

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#35]
As a **user** I can **delete a workout** so that **it can be entirely deleted from the database**
# Tasks
- [x] Add a delete_workout view to the main app
- [ ] Add the url to the urls.py
- [ ] Edit the workouts.html file to contain the delete workout feature
  
# Acceptance Criteria
- A workout can be deleted from the workout list

# Epic
Belongs to Epic #8
