### ISSUE TITLE
USER STORY: Session page

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#39]
As a **user** I can **view a session** so that **I can easily use the app at the gym**
# Tasks
- [x] create the model for sessions
- [x] create a view for a session
- [x] create a template for viewing a session
- [x] add sessions to the admin page
- [x] adjust the link on the calendar to go to the session page instead of edit session
- [x] test feature
  
# Acceptance Criteria
- The session page is rendered successfully
- The workouts added to the session is visual on the session page
- The session can be edited by clicking a link to the edit session page
# Epic
Belongs to Epic #7
