### ISSUE TITLE
TO DO: Style pages in the same fashion as the session page

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#44]
#Tasks
- [x] Style the authorized landing page / calendar
- [x] style the Workouts page
- [x] style the Workout form
- [x] style the Exercise page
- [x] style the exercise form
- [x] style the session form

# Acceptance Criteria
- all pages has an appealing look which is consistent over all pages
# Epic
Belongs to Epic #
