### ISSUE TITLE
USER STORY: User autentication

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#48]
As a **user** I can **sign up/ login** so that **I can use the features of the app**
# Tasks
- [ ] Set up the django authentication settings 
- [ ] Add django auth urls
- [ ] Create Sign up and login templates
- [ ] Create a registration view
- [ ] Add login/sign up logout logged in user to the navbar
  
# Acceptance Criteria
- The user can create an user account
- the user can login
- The user can logout
- The user sees the logged in user name in the navbar
-
# Epic
Belongs to Epic #4
