### ISSUE TITLE
USER STORY: View/create/edit and delete Muscle groups

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#52]
As an **authorized user** I can **add muscle groups** so that **I can reuse them in workouts**

# Tasks
- [x] add a muscle group model to the setup app
- [x] add a view for viewing musclegroups
- [x] add a musclegroup form
- [x] add a view for creating a musclegroup
- [x] add a view for editing a musclegroup
- [x] add  urls for viewing, creating, editing and deleting musclegroups
- [x] add templates for viewing, creating and editing muscle groups.
- [x] Add muscle groups to admin.py
  
# Acceptance Criteria
- I can ctreate, edit and delete musclegroups as an authorized user

# Epic
Belongs to Epic #12
