### ISSUE TITLE
USER STORY: Delete sessions

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#53]
As an **authorized user** I can **delete session** so that **they will be completely erased from the database**
# Tasks
- [ ] Add delete button on the session page
- [ ] Add a delete session view
- [ ] Add a delete session url
  
# Acceptance Criteria
- A session can be deleted from its session page
- 
# Epic
Belongs to Epic #7
