### ISSUE TITLE
USER STORY: Add muscle groups to Exercises

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#54]
As an **authorized user** I can **add muscle groups to my exercises** so that **filter my exercises by them**
# Tasks
- [ ] Add muscle group fk to the exercise model
- [ ] Add muscle group to the exercise form
- [ ] Update exercises.html with the muscle group
  
# Acceptance Criteria
- I can add muscle groups to exercises and see them on the exercise list and in my workouts.
-
# Epic
Belongs to Epic #9
