### ISSUE TITLE
TO DO: Compress background image

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#56]
#Tasks
- [x] Compress background image
- [ ] ~~Add more compressed images for different screensizes~~
- [x] remove background image for small size screens

# Acceptance Criteria
- The background image is optimized for different screen sizes to speed up rendering.

# Epic
Belongs to Epic #
