### ISSUE TITLE
TO DO: Test code

### ISSUE THREAD

**Issue by Odden69** [Odden69/ITrain#63]
#Tasks
- [x] Test all HTML code
- [x] Test CSS code
- [x] Test Python code
- [x] Test Javascript code

# Acceptance Criteria
- All test passes without errors

# Epic
Belongs to Epic #1

**Comment by Odden69** [comment]
Two errors were found on the HTML code.

One coming from the default django sign up page.

The other was a stray div end tag. After quite a lot of searching I left this issue since I could not see it had any effect on the rendering of the page.
